# Generated by Django 5.1 on 2025-01-23 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, null=True)),
                ('descripcion_receta', models.TextField(null=True)),
                ('medicacion_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('medicacion_dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('medicacion_frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('medicacion_duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
