# Generated by Django 5.1 on 2025-01-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='paciente',
        ),
    ]
