# Generated by Django 5.1 on 2025-01-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=50, null=True)),
                ('descripcion_especialidad', models.TextField(null=True)),
                ('fecha_registro', models.DateField(null=True)),
            ],
        ),
    ]
