# Generated by Django 5.1 on 2025-01-23 00:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('estado_covid', models.CharField(choices=[('S', 'Presenta síntomas'), ('N', 'No presenta síntomas')], default='N', max_length=1)),
                ('cita_duracion', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('hora_cita', models.TimeField(null=True)),
                ('atendida', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
