# Generated by Django 5.1 on 2025-01-23 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50, null=True)),
                ('cedula', models.CharField(max_length=20, null=True)),
                ('correo_electronico', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Dado de baja', 'Dado de baja')], default='Activo', max_length=15)),
                ('especialidad', models.ManyToManyField(to='especialidades.especialidades')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
