# Generated by Django 5.1 on 2025-02-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarioDisponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendariodisponibilidad',
            old_name='fecha_disponibilidad',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='calendariodisponibilidad',
            name='es_emergencia',
        ),
        migrations.RemoveField(
            model_name='calendariodisponibilidad',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='calendariodisponibilidad',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='calendariodisponibilidad',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
